### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [jangkuw/prj-rev-bwfs-dasmoto#5]
Grade: **Meets Expectations**

Overall this project is working great. Your HTML is very clean! You used `alt` attributes on all of your images which is great for accessibility. On top of all of this, the website is matching the specification which is always good to see. A couple things I would change about this project is making sure you link your images properly so they can be viewed by anyone else who has downloaded your project. Additionally, I would review your CSS properties to make sure they are the correct property for what you're trying to accomplish. After all of this, I would look into learning about media queries in an effort to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

Excellent work!

**Comment by jangkuw** [comment]
Thank you!    I have looked into media queries but am still confused.
